version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    command: streamlit run app/run_app.py --server.port 8500
    ports:
      - "8500:8500"
    volumes:
      - .:/app
