name: Build and deploy container app to Azure Web App - fire-forest-webapp-mlops

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v2
      with:
        registry: https://aabkeropscontainerregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_577eebf5741941e0986f768420121ebc }}
        password: ${{ secrets.AzureAppService_ContainerPassword_871f0d1612c943099605e4d5124fcb2c }}

    - name: Build and push Streamlit image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile.streamlit
        push: true
        tags: aabkeropscontainerregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_577eebf5741941e0986f768420121ebc }}/fastapi streamlit:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'fire-forest-webapp-mlops'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5574b1cd509b4baf99a619efa7d6e2ce }}
        images: 'aabkeropscontainerregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_577eebf5741941e0986f768420121ebc }}/fastapi streamlit:${{ github.sha }}'