name: Build and deploy container app to Azure Web App - fire-forest-webapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://aabkeropscontainerregistry.azurecr.io/
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push FastAPI image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile.fastapi
        push: true
        tags: aabkeropscontainerregistry.azurecr.io/fastapi:${{ github.sha }}

    - name: Build and push Streamlit image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile.streamlit
        push: true
        tags: aabkeropscontainerregistry.azurecr.io/streamlit:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'fire-forest-webapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: |
          aabkeropscontainerregistry.azurecr.io/fastapi:${{ github.sha }}
          aabkeropscontainerregistry.azurecr.io/streamlit:${{ github.sha }}
