# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - fire-forest-webapp-mlops

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://aabkeropscontainerregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_ea1c055c34214d4089a1e15c0eba5a7e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_66b0fcce76984151ba5347ca3cb9e380 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: aabkeropscontainerregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ea1c055c34214d4089a1e15c0eba5a7e }}/mlops-fireforest:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'fire-forest-webapp-mlops'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b7db421188df4c3ab211598bd54317a8 }}
        images: 'aabkeropscontainerregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ea1c055c34214d4089a1e15c0eba5a7e }}/mlops-fireforest:${{ github.sha }}'